services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: nexi
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
